name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Permissões necessárias para criar releases

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Debug Token
        run: echo "Token: ${{ secrets.GITHUB_TOKEN }}" | wc -c
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Add new features
            - Fix bugs
            - Update documentation
          draft: false
          prerelease: false
